services:
  nginx:
    image: "nginx:1.27.1-alpine-slim"
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./app:/srv/app:ro
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
