# This rule is not used by the project deploysyncer-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the deploy.example.com.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: deploysyncer-operator
    app.kubernetes.io/managed-by: kustomize
  name: deploysyncer-editor-role
rules:
- apiGroups:
  - deploy.example.com
  resources:
  - deploysyncers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - deploy.example.com
  resources:
  - deploysyncers/status
  verbs:
  - get
