---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - deploy.example.com
  resources:
  - deploysyncers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - deploy.example.com
  resources:
  - deploysyncers/finalizers
  verbs:
  - update
- apiGroups:
  - deploy.example.com
  resources:
  - deploysyncers/status
  verbs:
  - get
  - patch
  - update
