services:
  app1:
    image: "nginx:1.27.1-alpine-slim"
    container_name: app1
    volumes:
      - ./app1/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./app1:/srv/app:ro
    networks:
      - app-network
  app2:
    image: "nginx:1.27.1-alpine-slim"
    container_name: app2
    volumes:
      - ./app2/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./app2:/srv/app:ro
    networks:
      - app-network
  nginx:
    image: "nginx:1.27.1-alpine-slim"
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
