services:
  api:
    build:
      context: ./api
    container_name: api
    command: npm start
    networks:
      - app-network

  nginx:
    image: "nginx:1.27.1-alpine-slim"
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/nginx-selfsigned.crt:/etc/nginx/ssl/nginx-selfsigned.crt:ro
      - ./nginx/nginx-selfsigned.key:/etc/nginx/ssl/nginx-selfsigned.key:ro
    ports:
      - "80:80"
      - "3000:443"
    depends_on:
      - api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
